### ISSUE TITLE
Add docs to github too?

### ISSUE THREAD

**Issue by lgg** [AppCraft-LLC/pubg#1]
Is there any plans to add docs to github?

**Comment by KristobalJunta** [comment]
I +1 this.
Already found some errors/typos in the docs and feel not too comfortable to spam support email with all that.

**Comment by AppCraft-LLC** [comment]
Done 👍

**Comment by KristobalJunta** [comment]
Can you provide a link to the repo, please, can't find it in your github profile or in the pubg repo itself.

**Comment by lgg** [comment]
@KristobalJunta they made it as wiki: https://github.com/AppCraft-LLC/pubg/wiki
